spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/savepost
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: post-service

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG
