spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
  h2:
    console:
      path: /paging
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:../database/paging
    hikari:
      username: sa
      password:

logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: TRACE
