spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    hikari:
      username: postgres
      password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      port: 6379
      host: localhost